language: python
python: '2.7'

services:
  - docker
  - postgresql

env:
  global:
    - ID_DATABASE_URL=postgresql://postgres@localhost/id_test
    - ID_DOCUMENT_PATH=/tmp/

before_script:
  - docker-compose build
  - psql -c 'create database id_test;' -U postgres
  - python manage.py migrate

install:
  - pip install -r requirements-testing.txt

script: flake8 . && ./manage.py test

notifications:
  email: false

cache:
  pip: true
