notifications:
  email: false

services:
  - docker

before_script:
  - ln -s docker-compose.dev.yml docker-compose.yml
  - docker-compose build --build-arg=ID_VERSION=$(git describe --always) api
  - docker-compose up -d
  - docker-compose exec api sh -c "while ! nc -z postgres 5432; do sleep 0.1 ; done"
  - docker-compose exec -e DJANGO_SECRET_KEY=_ api python manage.py migrate --configuration=Production

script: docker-compose exec -e DJANGO_SECRET_KEY=_ api sh -c "pip install --no-cache-dir -r requirements-testing.txt && flake8 && python manage.py test"
