language: python
python: '2.7'
services: postgresql
before_script:
  - psql -c 'create database id_test;' -U postgres
env:
  - ID_SECRET_KEY=`openssl rand -hex 24`
  - ID_DATABASE_URL=postgresql://postgres@localhost/id_test
  - ID_DOCUMENT_PATH=/tmp/
install:
  - 'pip install -r requirements.txt'
  - 'python manage.py migrate'
script: 'python manage.py test api_v3.tests'
