language: python
python: '2.7'
services: postgresql
env:
  global:
    - ID_DATABASE_URL=postgresql://postgres@localhost/id_test
    - ID_DOCUMENT_PATH=/tmp/
install:
  - pip install -r requirements.txt
  - npm install --unsafe-perm
  - cd static && bower --allow-root --quiet --config.interactive=false --force install
before_script:
  - psql -c 'create database id_test;' -U postgres
  - python manage.py migrate
script: python manage.py test
