version: '2'

services:
  postgres:
    image: postgres:9.4-alpine
  web:
    restart: always
    environment:
      - DJANGO_SECRET_KEY=local
    image: web
    build: ./
    command: >
      sh -c "pip install -r requirements-testing.txt &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/id
    ports:
      - "8000:8000"
    depends_on:
      - postgres
