# Docker compose config
# http://docs.docker.com/compose/
version: "2"

networks:
  serverconfig_frontend:
    external:
      name: serverconfig_frontend
  id2internal:
    driver: bridge

services:
  postgres:
    image: postgres:9.4
    volumes:
      - '/srv/data/live/postgres/id2/:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER:     id2
      POSTGRES_PASSWORD: id2
      POSTGRES_DATABASE: id2
    networks:
      - id2internal

  web:
    restart: always
    image: web
    build: ./
    command: gunicorn -w 5 -b 0.0.0.0:8000 -t 60 --keep-alive 5 --log-level info --log-file - wsgi:application
    volumes:
      - "/srv/data/live/podaci/:/id/data"
      - "/srv/logs/id2/:/var/log/id2/"
      - "/srv/data/dumps/:/dumps/"
      - "/srv/data/live/idstatic/:/id/build/"
    env_file:
      - id.env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    links:
      - postgres
    networks:
      - serverconfig_frontend
      - id2internal
